name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24.4.1'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.12.1
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Validate presentations
      run: npm run validate
      
    - name: Build all presentations
      run: npm run build:all
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: presentations
        path: dist/
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: presentations
        path: dist/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist